### ISSUE TITLE
Advantages/Differences of HPC netCDF-C

### ISSUE THREAD

**Issue by mathomp4** [NOAA-GSD/netcdf-c#1]
This is just a general question: I was wondering what are the

> additional performance enhancements and features useful to the High Performance Computing (HPC) community

in this repo compared to Unidata/netcdf-c?

**Comment by mathomp4** [comment]
@edhartnett I thought that was the main difference, but I wasn't sure if there was anything else from HDF5 like:
- SWMR
- Collective Metadata I/O
- Easier non-default compression algorithm use
- Any thing else they advertised with 1.10

**Comment by edhartnett** [comment]
NetCDF does collective metadata IO already.

I have not looked into new HDF5 features yet. What is SWMR?

**Comment by edwardhartnett** [comment]
I am going to close this issue. All the advanced features of HPC netcdf have been merged into either netCDF or PIO.
